-- MySQL Script generated by MySQL Workbench
-- петак, 08. децембар 2017. 00:04:42 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`StatusRezervacije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusRezervacije` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `opis` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `jmbg` BIGINT(13) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NULL,
  `adresa` VARCHAR(75) NULL,
  `grad` VARCHAR(45) NULL,
  `postanskiKod` INT NULL,
  `drzava` VARCHAR(75) NULL,
  `brojMobilnogTelefona` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pol` VARCHAR(10) NULL,
  PRIMARY KEY (`jmbg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klijent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klijent` (
  `jmbg` BIGINT(13) NOT NULL,
  `brojKucnogTelefona` VARCHAR(45) NULL,
  `brojLicneKarte` VARCHAR(45) NULL,
  `brojPasosa` VARCHAR(45) NULL,
  PRIMARY KEY (`jmbg`),
  CONSTRAINT `fk_Gost_Osoba1`
    FOREIGN KEY (`jmbg`)
    REFERENCES `mydb`.`Osoba` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma` (
  `idFirme` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  `postanskiKod` INT NULL,
  `grad` VARCHAR(45) NULL,
  `drzava` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `osnovnaDelatnost` VARCHAR(255) NULL,
  `sifraDelatnosti` VARCHAR(45) NULL,
  `maticniBroj` VARCHAR(45) NULL,
  `webAdresa` VARCHAR(45) NULL,
  `brojRacuna` VARCHAR(155) NULL,
  PRIMARY KEY (`idFirme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agent` (
  `jmbg` BIGINT(13) NOT NULL,
  `idFirme` INT NOT NULL,
  PRIMARY KEY (`jmbg`),
  INDEX `fk_Agent_Firma1_idx` (`idFirme` ASC),
  CONSTRAINT `fk_Agent_Osoba1`
    FOREIGN KEY (`jmbg`)
    REFERENCES `mydb`.`Osoba` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agent_Firma1`
    FOREIGN KEY (`idFirme`)
    REFERENCES `mydb`.`Firma` (`idFirme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipSobe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipSobe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipSobe` VARCHAR(45) NULL,
  `opis` VARCHAR(100) NULL,
  `cenaNocenja` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezervacija` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datumPocetka` DATE NULL,
  `datumZavrsetka` DATE NULL,
  `brojSoba` INT NULL,
  `idStatusaRezervacije` INT NOT NULL,
  `idKlijenta` BIGINT(13) NOT NULL,
  `idAgenta` BIGINT(13) NULL,
  `idTipaSobe` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rezervacija_StatusRezervacije_idx` (`idStatusaRezervacije` ASC),
  INDEX `fk_Rezervacija_Gost1_idx` (`idKlijenta` ASC),
  INDEX `fk_Rezervacija_Agent1_idx` (`idAgenta` ASC),
  INDEX `fk_Rezervacija_TipSobe1_idx` (`idTipaSobe` ASC),
  CONSTRAINT `fk_Rezervacija_StatusRezervacije`
    FOREIGN KEY (`idStatusaRezervacije`)
    REFERENCES `mydb`.`StatusRezervacije` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervacija_Gost1`
    FOREIGN KEY (`idKlijenta`)
    REFERENCES `mydb`.`Klijent` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervacija_Agent1`
    FOREIGN KEY (`idAgenta`)
    REFERENCES `mydb`.`Agent` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervacija_TipSobe1`
    FOREIGN KEY (`idTipaSobe`)
    REFERENCES `mydb`.`TipSobe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Soba` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sprat` INT NULL,
  `opis` VARCHAR(100) NULL,
  `idTipaSobe` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Soba_tipSobe1_idx` (`idTipaSobe` ASC),
  CONSTRAINT `fk_Soba_tipSobe1`
    FOREIGN KEY (`idTipaSobe`)
    REFERENCES `mydb`.`TipSobe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RezervisanaSoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RezervisanaSoba` (
  `idRezervacije` INT NOT NULL,
  `idSobe` INT NOT NULL,
  `datum` DATETIME NULL,
  PRIMARY KEY (`idRezervacije`, `idSobe`),
  INDEX `fk_Rezervacija_has_Soba_Soba1_idx` (`idSobe` ASC),
  INDEX `fk_Rezervacija_has_Soba_Rezervacija1_idx` (`idRezervacije` ASC),
  CONSTRAINT `fk_Rezervacija_has_Soba_Rezervacija1`
    FOREIGN KEY (`idRezervacije`)
    REFERENCES `mydb`.`Rezervacija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervacija_has_Soba_Soba1`
    FOREIGN KEY (`idSobe`)
    REFERENCES `mydb`.`Soba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipPlacanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipPlacanja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipPlacanja` VARCHAR(45) NULL,
  `opis` VARCHAR(105) NULL,
  `aktivno` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Placanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Placanje` (
  `idTipaPlacanja` INT NOT NULL,
  `obavljeno` TINYINT NULL,
  `suma` FLOAT NULL,
  `datum` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idRezervacije` INT NOT NULL,
  INDEX `fk_Placanje_TipPlacanja1_idx` (`idTipaPlacanja` ASC),
  PRIMARY KEY (`idRezervacije`),
  CONSTRAINT `fk_Placanje_TipPlacanja1`
    FOREIGN KEY (`idTipaPlacanja`)
    REFERENCES `mydb`.`TipPlacanja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Placanje_Rezervacija1`
    FOREIGN KEY (`idRezervacije`)
    REFERENCES `mydb`.`Rezervacija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoblje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoblje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `adresa` VARCHAR(75) NULL,
  `grad` VARCHAR(45) NULL,
  `postanskiKod` INT NULL,
  `drzava` VARCHAR(75) NULL,
  `brojTelefona` VARCHAR(45) NULL,
  `pol` VARCHAR(10) NULL,
  `jmbg` INT(13) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pozicija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pozicija` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `opis` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odeljenje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odeljenje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `opis` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pripada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pripada` (
  `idOsoblja` INT NOT NULL,
  `idOdeljenja` INT NOT NULL,
  `idPozicije` INT NOT NULL,
  PRIMARY KEY (`idOsoblja`, `idOdeljenja`),
  INDEX `fk_Osoblje_has_odeljenje_odeljenje1_idx` (`idOdeljenja` ASC),
  INDEX `fk_Osoblje_has_odeljenje_Osoblje1_idx` (`idOsoblja` ASC),
  INDEX `fk_Osoblje_has_odeljenje_Pozicija1_idx` (`idPozicije` ASC),
  CONSTRAINT `fk_Osoblje_has_odeljenje_Osoblje1`
    FOREIGN KEY (`idOsoblja`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoblje_has_odeljenje_odeljenje1`
    FOREIGN KEY (`idOdeljenja`)
    REFERENCES `mydb`.`Odeljenje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoblje_has_odeljenje_Pozicija1`
    FOREIGN KEY (`idPozicije`)
    REFERENCES `mydb`.`Pozicija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DodeljenaSoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DodeljenaSoba` (
  `idOsoblja` INT NOT NULL,
  `idSobe` INT NOT NULL,
  PRIMARY KEY (`idOsoblja`),
  INDEX `fk_Osoblje_has_Soba_Soba1_idx` (`idSobe` ASC),
  INDEX `fk_Osoblje_has_Soba_Osoblje1_idx` (`idOsoblja` ASC),
  CONSTRAINT `fk_Osoblje_has_Soba_Osoblje1`
    FOREIGN KEY (`idOsoblja`)
    REFERENCES `mydb`.`Osoblje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoblje_has_Soba_Soba1`
    FOREIGN KEY (`idSobe`)
    REFERENCES `mydb`.`Soba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
